### ISSUE TITLE
Can not close eye.

### ISSUE THREAD

**Issue by lyyiangang** [ascust/3DMM-Fitting-Pytorch#1]
Thanks for your repo first.
I find the closed eye can not be fit.
Input :
![image](https://user-images.githubusercontent.com/1982228/112420482-3cbbfc00-8d68-11eb-8191-c298492e7e84.png)
Output:
![image](https://user-images.githubusercontent.com/1982228/112420504-46ddfa80-8d68-11eb-9a65-7b9efa966b11.png)

The question is how to make the eyes close?

**Comment by ascust** [comment]
As far as I know, the 3DMM model used in this project is not good at fitting closed eyes. I think it is because the expression bases can not cover all the expressions. For some special expressions like "close one eye with the other open", it is rather difficult to find an expression vector.

**Comment by lyyiangang** [comment]
@ascust  thanks for your advice.
