### ISSUE TITLE
Is the point in BFM have the same sequence of extra expression basis？

### ISSUE THREAD

**Issue by nxsf8023** [ascust/3DMM-Fitting-Pytorch#11]
Now I make a group of exp basis data by myself. And I want to add it in extra expression basis.
Should I must use the same point sequence of BFM? If I must do this, how can I transform my own data?
Thx.

**Comment by ascust** [comment]
Are you going to add extra expression bases to the current BFM09? If so, I think you should make sure:
1. the number of vertices is equal to that of the current BFM09.
2. the topology of the vertices is the same.
3. the vertices are well aligned to the current model.

**Comment by nxsf8023** [comment]
Yes, I try to use the way in FaceWarehouse to add extra expression to BFM09. And use "Deformation Transfer for Triangle Meshes" to change my model's topology to suit BFM09.
I also want to know could I use this way on BFM_2017/BFM_2019, if I do this, how could I get the tri of BFM_2017/2019.Because without this, I can't gen my own BFM2017/2019 .obj file.
Thx for your reply.

**Comment by nxsf8023** [comment]
I also want to ask a question, is the triangles in BFM2017 is wrong?

**Comment by ascust** [comment]
> Yes, I try to use the way in FaceWarehouse to add extra expression to BFM09. And use "Deformation Transfer for Triangle Meshes" to change my model's topology to suit BFM09.
> I also want to know could I use this way on BFM_2017/BFM_2019, if I do this, how could I get the tri of BFM_2017/2019.Because without this, I can't gen my own BFM2017/2019 .obj file.
> Thx for your reply.

I am not sure what you mean by "get the tri of BFM17/19". Isnt the info of triangles supposed to be included in the 17/19 model file?

**Comment by ascust** [comment]
> I also want to ask a question, is the triangles in BFM2017 is wrong?

Not sure about this either. Why are the triangles in BFM2017 wrong?

**Comment by nxsf8023** [comment]
I have solve it now. I find that the tri in BFM2017 is cells. 
And if I want use this data to generate a mean BFM2017 .obj file, must add 1 to every tri, and have to write every tri reverse to file. 
Do this I get a correct .obj file at last.
Thx for your help very much!
