### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'BFM/BFM09_model_info.mat'

### ISSUE THREAD

**Issue by BuyingANew-Soul** [ascust/3DMM-Fitting-Pytorch#12]
I'm trying to use the fit_single_img.py but getting the above error. How can I solve this issue?

**Comment by UttaranB127** [comment]
I faced the same issue. In case anyone else comes across this, the solution is to run [convert_bfm09_data.py](https://github.com/ascust/3DMM-Fitting-Pytorch/blob/master/convert_bfm09_data.py). Requesting the authors to add it to the readme as it is a required step. Please also refer to issue #15 regarding the correct address of the [Exp_Pca.bin](https://github.com/Juyong/3DFace/raw/master/Exp_Pca.bin) file to download.
