### ISSUE TITLE
Rigid fitting have some wrong by BFM2019 data.

### ISSUE THREAD

**Issue by nxsf8023** [ascust/3DMM-Fitting-Pytorch#13]

**Comment by nxsf8023** [comment]
Now I have generate my own BFM2019 data, and when I run rigid fitting step, I find that the result is wrong, but the loss is low.
Could you give me some suggestion please? 
Thank you very much!

**Comment by ascust** [comment]
Hi, Could you be more specific about how you generated your own BFM2019 data?  Did you get the correct correspondence between the 68 2d landmarks and the vertices on the mesh?

**Comment by nxsf8023** [comment]
> 
> 
> Hi, Could you be more specific about how you generated your own BFM2019 data? Did you get the correct correspondence between the 68 2d landmarks and the vertices on the mesh?

Thanks for replying. I have solved this problem. The index of landmarks in your code is from 1, but main is from 0.
Now I can continue to develop it.

**Comment by Robin970822** [comment]
> > Hi, Could you be more specific about how you generated your own BFM2019 data? Did you get the correct correspondence between the 68 2d landmarks and the vertices on the mesh?
> 
> Thanks for replying. I have solved this problem. The index of landmarks in your code is from 1, but main is from 0. Now I can continue to develop it.

I noticed that you are using BFM2019 instead of BFM2009, whose correspondences between the 68 2d landmarks and the vertices on the mesh are different. Do you have the landmarks indexes of 68 2d landmarks corresponding to the BFM2019?
