### ISSUE TITLE
some question about code

### ISSUE THREAD

**Issue by UestcJay** [ascust/3DMM-Fitting-Pytorch#17]
`  vs = torch.matmul(vs, self.reverse_z.repeat((batchsize, 1, 1))) + self.camera_pos
     
aug_projection = torch.matmul(vs, self.p_mat.repeat((batchsize, 1, 1)).permute((0, 2, 1)))`
Hi, many thanks for your great work!  I don’t know if I understand it right, the first line represents the orthographic projection? The second line indicates that the picture coordinate system is converted to the pixel coordinate system?

**Comment by ascust** [comment]
Hi,
The first line is to:
1. reverse the z direction.
2. take the camera position into consideration.

So it basically transforms the world coords to cam coords.

The second line performs the projection, meaning converting 3d coords to 2d coords.
