### ISSUE TITLE
why the 3DMM fitting face does not look like the input image?

### ISSUE THREAD

**Issue by Randa-NACHET** [ascust/3DMM-Fitting-Pytorch#18]
Thank you for sharing your work, please which parameters exactly correspond to obtain a good result ( preserved identity) and on what basis should I modify), because the output image does not look like the input (very smooth).

**Comment by ascust** [comment]
Hi, are you talking about the texture? or the geometry of the mesh? Since the optimized mesh is still a linear combination of the basis meshes, you would not expect an identical one.

**Comment by lvZic** [comment]
> Hi, are you talking about the texture? or the geometry of the mesh? Since the optimized mesh is still a linear combination of the basis meshes, you would not expect an identical one.

hi, is there anything that could improve the identical?

**Comment by ascust** [comment]
@lvZic The quality is highly limited by the 3DMM model itself, which means if we cannot find a similar texture in the texture space, or shape in the shape space, we might not get a face that assembles the face in the image.
