### ISSUE TITLE
Why the face_shape need to minus the mean of meanshape?

### ISSUE THREAD

**Issue by linziqu** [ascust/3DMM-Fitting-Pytorch#19]
Hi, thanks for your work!
I am wonder why the function in BFM09ReconModel below?
face_shape = face_shape - \
            self.meanshape.view(1, -1, 3).mean(dim=1, keepdim=True)

**Comment by ascust** [comment]
Hi,actually I followed someone else's procedure. It is just used to move the whole mesh a bit so that the origin is at round the center of the mesh.
