### ISSUE TITLE
How to get 'facemodel_info.mat'

### ISSUE THREAD

**Issue by guoyi11** [ascust/3DMM-Fitting-Pytorch#2]
Hi~

Thanks for this wonderful repo.
I notice that there is file named 'facemodel_info.mat', and we have to build the bfm model using this file. I'm wondering how to get this file. Especially I don't understand what 'point_buf' means. It seems 'point_buf' is used to compute the surface norm. But could you provide more information/explanation about this file? Thank you.

**Comment by guoyi11** [comment]
I find the explanation in Deep3DFaceReconstruction. It means the adjacent face index for each vertex

**Comment by HDYYZDN** [comment]
> 我在Deep3DFaceReconstruction中找到了解释。它表示每个顶点的相邻面索引

想问一下，这个文件是怎么生成的，您知道吗？？？
