### ISSUE TITLE
Could you please share the code to generate the GIF of fitting process ?

### ISSUE THREAD

**Issue by wwdok** [ascust/3DMM-Fitting-Pytorch#22]
Like this gif:https://github.com/ascust/3DMM-Fitting-Pytorch/blob/master/gifs/demo.gif

**Comment by ascust** [comment]
Do you mean how to paste the fitting result back to the original image?

**Comment by wwdok** [comment]
Yes, almost that meaning, but also compose the whole fitting process as a animation to a GIF image

**Comment by ascust** [comment]
The GIF was not generated by code. I just saved all the frames, composed them into a video and converted it using some off-the-shelf tool. The only thing you need to do is to refer to the part (starting from line 116 in "fit_single_img.py" ) of saving the results and insert it into the fitting loop. Thats it.

**Comment by wwdok** [comment]
Ok, i got it, thanks !
