### ISSUE TITLE
Texture refering to vertex colors ?

### ISSUE THREAD

**Issue by Kiord** [ascust/3DMM-Fitting-Pytorch#23]
Hello, 
I am trying to use my own statistical model with your code.
What is exactly is `face_texture` in `BFM09ReconModel.forward` ? I have dimensions incompatibility with a tensor of texture so I suspect it actually refers to vertex colors. correct ? 

Also, what is `BFM09ReconModel.point_buf` ?

**Comment by ascust** [comment]
Hi, sorry for the late reply. `face_texture` actually describes the RGB of each vertex. The dimensions are the same as `vs` So if you use your own model, only make sure the dimensions match.

About `point_buf`, it represents the face ids of each vertex it is adjacent if I remember it correctly.
