### ISSUE TITLE
How to Train Our Own Data

### ISSUE THREAD

**Issue by Bai426** [ascust/3DMM-Fitting-Pytorch#24]
Hi, ascust, this repository is great. I am wondering how to prepare and train my own data if I want to not only reconstrct face but other components of a head？

**Comment by ascust** [comment]
@Bai426 Hi, thanks for the interest. The reconstruction process is actually based on the statistical model you use. In this repo, I used BFM, which is a 3DMM model created by scanning many faces. If you want to reconstruct the full head, you need to find a 3DMM model that provides a full head. What the code does here is simply finding the best parameters(shape, expression, poses, etc.) to match the given face images. So long story short, what you can do largely depends on what the face model provides.

**Comment by Bai426** [comment]
Yes, that makes sense. Thank you very much for your reply and suggestions.
