### ISSUE TITLE
how to fit to rgbd data

### ISSUE THREAD

**Issue by rlczddl** [ascust/3DMM-Fitting-Pytorch#25]
Hi, ascust,  this repository is great. I am wondering how to modify the code to fit rgb+depth data using the real camera parameters?

**Comment by ascust** [comment]
Hi, it seems like adding a depth channel would enable 3D landmark fitting. The current landmark loss only assumes 2d landmark, so you might need to use a 3d landmark detector. Furthermore, for RGB pixel fitting, apart from fitting three color channels, you could also add a depth loss for each vertex projected to the image. 

Not sure if I've made myself clear.

**Comment by rlczddl** [comment]
Thanks for your reply. In fact, what I want is to fit the point-to-point error between bfm 3d face shape and point cloud converted from depth image, not just the depth error between face key points.And now, referring to https://github.com/yuhaoooo/Deep3DFaceReconstruction-Pytorch/blob/7c506b55adee55bb269f73354dd16d5327a7fb04/reconstruction_mesh.py , I have some ideas.

**Comment by rlczddl** [comment]
Hi, I'm modifying the code to fit bfm to rgbd data. Unfortunately I ran into some problems. In the rigid fitting stage, I use the real camera parameter K from the calibration, and since the scale of the bfm face model is unknown,  an additional scale parameter s is optimized. Now the projection equation of the 2d face keypoint is K(sR*p+T), but the optimization result of this step is always wrong. I don't know what went wrong. Do you have any suggestions? Here are some key codes:
![image](https://user-images.githubusercontent.com/21055131/191702552-d39d6d96-194f-4a94-a061-8572cc0d9045.png)
![image](https://user-images.githubusercontent.com/21055131/191702645-ccc22bd9-c89c-4a54-bca8-ea3009dc064f.png)
![image](https://user-images.githubusercontent.com/21055131/191702737-1727367d-c365-4e82-a494-85051e32a874.png)
![image](https://user-images.githubusercontent.com/21055131/191702835-27b7d235-20ed-4301-afb2-e54e4e0f1c8a.png)

**Comment by rlczddl** [comment]
After some debugging, I found that the initial z value on self.camera_pose must be set to an initial value instead of 0, which indicates the distance between the camera and the bfm model, so that the rigid part can be optimized. Why is this?

**Comment by ascust** [comment]
I am not really sure what is going on here. In terms of camera_pose z, I remember I set it to (0, 0, 10) and the camera is pointing at the origin (0, 0, -1). The reason for this is that the face mesh is supposed to be at the origin and given a proper focal length we can easily project the whole face on the image plane. If you put the camera at (0, 0, 0), it would be a bit weird because the camera and the mesh target are almost at the same point. Not sure if this is what you are talking about.

**Comment by rlczddl** [comment]
Thanks for your answer. After several days of debugging, the problem has been solved. Now I use the umeyama algorithm to initialize scale, R, T. After that, I encountered the problem mentioned by the issue https://github.com/facebookresearch/pytorch3d/issues/334 . Finally, I solved the problem by dividing the vertex by a fixed scale factor.
