### ISSUE TITLE
Why  should reverse z  and puls camera position?

### ISSUE THREAD

**Issue by shoutOutYangJie** [ascust/3DMM-Fitting-Pytorch#26]
Here is your code  
> face_shape = torch.matmul(face_shape,reverse_z) + camera_pos
I don't know what it really means？

**Comment by ascust** [comment]
This is used to transform the coordinates of the mesh from the world system to cameras local system.

**Comment by shoutOutYangJie** [comment]
but why not directly use rotation and translale matrix?




312358434
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ascust/3DMM-Fitting-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ascust/3DMM-Fitting-Pytorch] Why  should reverse z  and puls camera position? (Issue #26)





 
This is used to transform the coordinates of the mesh from the world system to cameras local system.

**Comment by ascust** [comment]
I am not really sure about your question. My understanding is that the rotation and translation matrices are defined in the global coordinates to alter mesh's pose. If you want to project the mesh to the camera (or any camera), you have to transform the coordinates to the camera's local ones and convert 3d points to 2d points to have them on the image plane.
