### ISSUE TITLE
How to output a face with ears and neck？

### ISSUE THREAD

**Issue by yuchen814** [ascust/3DMM-Fitting-Pytorch#27]
I used the bfm model with 53215 vertices and rewritten the point_ buf and skinmask in facemodel_info.mat run directly after that, but the results are not good. Here are some results. The texture seems to be fitted, but the shape and posture are very bad. 
![image](https://user-images.githubusercontent.com/114374394/216925723-341d124c-64e9-440d-b817-ee64dae0014c.png)
What can I do to rebuild a face with ears and neck? I would be very grateful if you could help me.

**Comment by ascust** [comment]
Hi, I am not quite sure what you have modified. Do you mean you use the full head model to replace the model used in the repo?

**Comment by yuchen814** [comment]
> 
Thank you for your reply.
Yes, I used BFM model in face3D. I think it is a full head model with ears and neck. And I changed point_buf  and skinmask in facemodel_info.mat. If I don't change the point_ buf, I can't run the code and calculate tex_ loss_ val.

**Comment by yuchen814** [comment]
> Hi, I am not quite sure what you have modified. Do you mean you use the full head model to replace the model used in the repo?
That's a BMF model in face3d, I didn't get it from the official website.
![image](https://user-images.githubusercontent.com/114374394/217179355-4f27ff3e-8739-4857-9a85-daabc3601d0d.png)

**Comment by yuchen814** [comment]
> Hi, I am not quite sure what you have modified. Do you mean you use the full head model to replace the model used in the repo?

That's a BMF model in face3d, I didn't get it from the official website.
![image](https://user-images.githubusercontent.com/114374394/217179880-adf8af45-7a97-43f9-bc28-9641cf4c0828.png)

**Comment by ascust** [comment]
> > 
> 
> Thank you for your reply. Yes, I used BFM model in face3D. I think it is a full head model with ears and neck. And I changed point_buf and skinmask in facemodel_info.mat. If I don't change the point_ buf, I can't run the code and calculate tex_ loss_ val.

Hi, I see what you are doing. The problem here is that the 3dmm model we use for fitting is a combination of two parts (a set of face shape basis from BFM09 and a set of expression basis from another source.) These two are both trimmed to get the one we use here. In order to make the full head work. You have to make sure the shape basis and the expression basis are mapped correctly and also the facial landmarks are correct (super important because the fitting process mainly relies on them)

**Comment by yuchen814** [comment]
> > > 
> > 
> > 
> > Thank you for your reply. Yes, I used BFM model in face3D. I think it is a full head model with ears and neck. And I changed point_buf and skinmask in facemodel_info.mat. If I don't change the point_ buf, I can't run the code and calculate tex_ loss_ val.
> 
> Hi, I see what you are doing. The problem here is that the 3dmm model we use for fitting is a combination of two parts (a set of face shape basis from BFM09 and a set of expression basis from another source.) These two are both trimmed to get the one we use here. In order to make the full head work. You have to make sure the shape basis and the expression basis are mapped correctly and also the facial landmarks are correct (super important because the fitting process mainly relies on them)

Thank you very much!!!!!!!!!!!!
I successfully reconstructed a complete face!!!!!!!!!!!
![b37343057dc767dcf439836c9ee7e93](https://user-images.githubusercontent.com/114374394/217823235-ea49b0f4-3f9e-4ee6-bbf5-5c8a50c3c279.png)

**Comment by yuchen814** [comment]
> 
I encountered another problem. The front of the obj model I produced is dark and the back is bright. Is the parameter "color" reversed? What can I do to correct it？
![image](https://user-images.githubusercontent.com/114374394/217825297-194bac41-563d-428a-822d-6acab180b5ce.png)
![image](https://user-images.githubusercontent.com/114374394/217825338-8d71701a-c21c-40f4-bdb6-5d84cfa1cf90.png)

**Comment by ascust** [comment]
Hi, I am guessing it is not about vertices' colors. It might be related to the face normals. When you write your model to the obj file (which actually writes vertex coordinates, face info and vertex color info into the file). Since the order of vertices of a face decides the face normal (clockwise or counter-clockwise), SO TRY REVERSING THE VERTEX ORDER OF THE FACE TRIANGLES WHEN EXPORTING THE OBJ.

**Comment by yuchen814** [comment]
Thank you very much for your reply. I will try later!!!!!!!!!!!!!!!

**Comment by WangXuan2401** [comment]
> 

Thank u ! I met the same problem. And I solved it now !

**Comment by skyler14** [comment]
Hey @yuchen814 or @WangXuan2401 do you guys have examples of the changes you made to get this working?

**Comment by WangXuan2401** [comment]
sorry, I didn't get the idea result with the model provided by another friend.


It seems the problem occurs in the pretrained model, but I am not sure.
---- Replied Message ----
| From | ***@***.***> |
| Date | 09/07/2023 15:55 |
| To | ascust/3DMM-Fitting-Pytorch ***@***.***> |
| Cc | Xuan ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [ascust/3DMM-Fitting-Pytorch] How to output a face with ears and neck？ (Issue #27) |

Hey @yuchen814 or @WangXuan2401 do you guys have examples of the changes you made to get this working?
