### ISSUE TITLE
question about fov 

### ISSUE THREAD

**Issue by ForrestPi** [ascust/3DMM-Fitting-Pytorch#4]
In the code set focal=1015,  Could you explain how to calculate the fov's value ?
And how to  use the real fov's value of the whole picture not the crop's picture ?

**Comment by ascust** [comment]
https://github.com/ascust/3DMM-Fitting-Pytorch/blob/f5c8dc66d5dfc71cbb9fe58c9c42a79029cef791/core/models.py#L57

The calculation of fov is here. 

Could you be more specific about your second question? Do you mean run fitting on the whole picture instead of the cropped image?

**Comment by ForrestPi** [comment]
@ascust 
So，how to get  focal=1015？
usually  the pipeline is blew
![fov](https://user-images.githubusercontent.com/12846142/118427868-c81a9380-b700-11eb-89c8-7540aeac89dd.jpg)

But we do this by  using the real fov's value of  the crop's picture not the whole picture,   we cannot render the whole picture in unity.

How to use the MVP in the whole picture

**Comment by ascust** [comment]
Do you mean that after the fitting stage (we have got the position and rotation of the face mesh), how can we render the whole body instead of the face region?
How about changing the position of the camera? meaning pulling the camera away from the face mesh?

**Comment by ForrestPi** [comment]
@ascust  yeah
we got the MVP matrix of the cropped face image not the whole picture , so we cannot not use the camera's fovx fovy.

**Comment by ascust** [comment]
sorry man, I am not really sure about the issue. If you what to see the whole picture, either pull the camera away from the object or change the focal length. Changing fov certainly can enlarge your view, but seems not a good way.
